module.exports =[
    'Lucu banget, harusnya aku ketawa bukan jatuh cinta',
    'Masih pagi sudah lucu, agak siangan dikit kayaknya sudah bikin sayang',
    'Allah sayang kamu, terus aku ikutan, gapapa kan ya?',
    'Are you some kind of rendang? Because you make my heart bergendang-gendang!',
    'Kayaknya rugi gak sih kalo kita gak pacaran?',
    'Punggungku bagus "kan, cocok untuk menjadi tulang keluarga kita 5 tahun lagi',
    'Botol galon diambil Bayu. How can I move on when I"m still in love with you',
    'Kamu mau gak jadi pacarku? Kalo nggak mau ya udah, biar aku aja yang jadi pacar kamu',
    'Tahu gak apa bedanya kamu sama pantun?Gak ada. Soalnya sama-sama cakep',
    'Bapak kamu tukang sushi yaaa?Soalnya kamu menggulung-gulung hatiku',
    'Ada yang kangen, tapi bukan Dewa 19, yaitu aku…',
    'Your last name must be "calendar", right? Because all I wanna ask you is "date"',
    'Are you born in 24 Juli? Because you are 24/7 for me',
    'Are you an omelette?',
    'Because you make me eggcited!',
    'I have a theory that your dad and my dad bakal besanan!',
    'Hape kamu search xiaomi, nomorku tri. Apakah kamu gak mau bareng sama aku agar menjadi xiaomistri?',
    'Kepala kamu kenapa bentuknya kaya gitu?',
    'Kaya kepala keluargaku 5 tahun kelak…',
    'Are you a keyboard?',
    'Because you are my type..',
    'Stop saying "be yourself" to me because I wanna be yours',
    'Lagi nyari restoran yang punya promo buy one get you',
    'What is your name?',
    'Uh…Can I call you mine?',
    'Aku rela ketusuk pisau demi kamu, asal gak kena…',
    'Jika buah mangga jatuh dari pohon dengan ketinggian 7 meter, dan buah mangga tersebut memiliki berat 1kg. Maka, berapakah nomor WhatsApp-mu?',
    'Are you some kind of balsem?Because you are so handsome…',
    'Kamu kalo bikin teh, gak usah dikasih gula.Cukup kamu senyumin aja…',
    'Kamu jangan suka begadang. Mending suka sama aku aja..',
    'Apa bedanya kamu sama DPR? Kalau DPR itu dewan perwakilan rakyat, kalau kamu dewan and only',
    'Are you some kind of nastar? Because you make my heart bergetar-getar…',
    'Senyum kamu jangan cerah-cerah dong, nanti mataharinya minder',
    'Kenapa Ultraman bunyinya "tinung-tinung"? Karena kalau bunyinya "Love You Love You" itu aku ke kamu…',
    'Astaga mubadzir banget orang secakep kamu tidak menjadi milikku…',
    'Ganteng/cantik sih, tapi sayang udah makan belum?',
    'Kalau laper masak mie, tapi kalau kangen call me aja',
    'Buat apa menghisap sabu, kalau lihat senyummu saja sudah candu..',
    'Kok orang-orang bisa ya kepikiran buat gombal, sedangkan di pikiranku cuma ada kamu…',
    'Apa bedanya jam 10 sama kamu? Kalau jam 10 itu kesiangan, tapi kalo kamu itu kesayangan',
    'Aku kalau disuruh berhenti mencintai kamu, aku mau ke kelurahan dulu.Mau buat surat keterangan tidak mampu…',
    ' Do you know the difference between you and number 9? Yes! Number 9 is nine,But if you are mine…',
    'Chatingan sama kamu kok serem ya, notifnya di hape tapi yang getar kok di hati aku…',
    'I like ppkm without "pp"…',
    'Masa sekarang alfabet tuh udah berubah. Tadinya kan abcdefghijklmn, sekarang jadinya abcdefghiloveyou…',
    'Do you like "anime" without "ani"…',
    'Kesel deh. Udah beli nasi goreng spesial mahal-mahal tapi yang spesial masih tetap kamu…',
    'Sarung atlas sarung wadimor',
    'Whatever your past, I always love you more…',
    'Pernah gak sih niatnya mau ngisi botol minum biar penuh tapi yang penuh malah cintaku ke kamu…',
    'Sarung atlas sarung wadimor. Whatever your past I always love you more',
    'Coba deh kamu minggir keselatan dulu, soalnya gabisan diutarakan rasa sayangnya…',
    'Apa kamu gak capek? Lari-lari terus di pikiranku…',
    'Yes i" wibu. Watashi Ingin Bersama mU',
    'Buku tulis, punya Buku gambar, ada Buku CPNS, di Gramedia,Buku nikah, yuk kita buat…',
    'Suka sih makan di Mcdonald"s Tapi aku lebih suka McYouFeelMyLove…',
    'Narkoba, NO Korupsi, NO Kalau kamu no WhatsApp-nya berapa…',
    'Do you love yourself?Yes.Ok then, we love the same person..',
    'Riset menunjukkan kalau orang keseringan duduk maka akan meningkatkan risiko kesemutan. Jadi, gimana kalau kita jalan aja?',
    'Gak mau sate, maunya sate(y) with you…',
    'Tuhan itu nomor satu, orang tua nomor dua, keluarga nomor tiga. Kalo kamu nomor WhatsApp-nya berapa?',
    'Apa beda kamu sama DPR?Kalau DPR dewan perwakilan rakyat, kalau kamu dewan n only…',
    'Ada galon diambil Bayu.How can I move on, when I am still in love you…',
    'Pada sebuah percobaan pelemparan 4 buah dadu secara bersamaan, coba hitung peluang aku untuk mendapatkan hatimu?',
    'Ingin tenang? Shalat lah!Ingin kaya? Bersedekah lah!Ingin aku? Chat aja lah!',
    'Alphabet start with A B C.Number start with 1 2 3,Melody start with do re mi.Can my love start with you and me?',
    'Daripada menjadi boyband, lebih baik menjadi my boyfriend saja…',
    'Mau tahu cara mutihin rambut secara alami dan permanen?Maka menualah bersamaku',
    'Bapak kamu kerja jadi ondel-ondel ya?Karena kamu telah me-ning-nang-ning-nung-kan hatiku…',
    'Minyak apa yang bikin mabuk?Minyaksikan (menyaksikan) senyummu setiap hari…',
    'Kalau Rama untuk Sinta,Kalau Jack untuk Rose,Kalau aku boleh untuk kamu tidak?',
    'Sending your selfie to NASA because you are my star',
    'Albert einstein said there"s nothing faster than light but clearly he hasn"t seen how fast I"ve fallen for you',
    'Pilih sianida, remidi kimia, atau aku yang selalu ada?',
    'Kalau lihat kamu selalu ingat pintu. Karena kamu a door able',
    'Pikachu. Pikiran kacau mikir kamu…',
    'Your wedding will be amazing, but "Y" is silent..',
    'Do you know I am a rainbow? Because I"m meijikuhibi-need you…',
    'January,February,March,April,May…I have crush on you',
    'Dua tiga ketupat cayul,Semoga perasaanku ini yang paling unggul',
    'Munduran sedikit dong. Karena cakepnya kamu kelewatan…',
    'I"m not perfect but I"m better than your ex, and gonna be better than your NEXT',
    'Antartika jauh. Tapi AntarKita jangan ya…',
    'Kamu tau kenapa HappyTos gambarnya jagung? Kalau diberi gambarku dan kamu nanti jadinya Happy Wedding…',
    'Is your face from McDonalds, because I"m lovin it',
    'Asked God for happiness, then He gave me you…',
    'Tangan kamu jangan dibuat main game terus ya, nanti kalau sakit, pas ijab qabul besok gimana?',
    'Tau gak apa bedanya film sama kamu? Kalau film tayang di bioskop, kalau kamu tayangnya aku…',
    'Knock knock,Who"s there?"Jo"...Jo who?..."Jodohmu kelak"..',
    'Kalau kita ini buah, kayanya kamu jadi timun deh. Karena kamu cute-cumber',
    'Your hand looks heavy, can I hold it for you?',
    'Somay, somay apa yang tulus?So may you marry me right now?',
    'Kamu percaya gak sama cinta pada pandangan pertama? Atau aku harus lewat lagi?',
    'Lho kok kamu masih ada di sini? Memang selendang kamu belum dikembaliin sama Jaka Tarub?',
    'Manis banget sih kamu, bikin pabrik Silverqueen bangkrut aja..',
    'Kalau mencintaimu merupakan kesalahan, kayanya aku gamau jadi bener aja deh',
    'Are you a volcano? Because I lava you…',
    'Are you some kind of bedug? Because you make my heart dag dig dug',
    'Maaf ya aku gak bisa gombalin kamu. Karena cintaku gak bisa buat gombal-gombalan, aku maunya seriusan…',
    'Aku tahu kita gak seumuran, tapi boleh gak aku minta waktu seumur hidup sama kamu…',
    'Can I follow you home? Because my parents always told me to follow my dreams.',
    'If I were a tear in your eye, I would roll down your cheek and die.',
    'Let"s play a game, but not hide and seek, because someone like you it"s hard to find',
    'I heard you are good at math. So, would you replace my X without asking Y?',
    'You look kinda mixed. half korean and half mine',
    'If i can rearrange the alphabets, i would put u and i together',
    'Lemme tell you the name of the month, january february march april may you be mine?',
    'Italy but the "ta" is silent',
    'Why do you have to be "boboiboy", when you can just "be my boy?"',
    'People said when you think happy thoughts, you fly. But why, when I think of you, I fall',
    'What is your favorite insect? Mine are the butterflies you give me',
    'Are your parents named practice? because they"ve made something perfect',
    'Di Indonesia itu waktunya ada WIT, WITA, dan WIB. Tapi aku sih lebih suka WIT U',
    "Kalo kamu wajan, aku itu margarin. Soalnya kalau deket kamu aku meleleh.",
    "Cuma ada 3 hal yang gak bisa aku hitung di dunia ini, jumlah bintang di langit, ikan di laut, dan rasa cinta aku ke kamu.",
    "Aku sadar kita memang gak seumuran, tapi aku mau seumur hidup dengan kamu.",
    "Kamu itu kayak skripsi, ya. Susah dimengerti, tapi harus diperjuangkan demi masa depan.",
    "Gimana kalo kita jadi komplotan pencuri? Aku curi hati kamu, kamu curi hati aku.",
    "Kursi makin lama makin antik, kalo kamu makin lama makin cantik.",
    "Gak perlu GR, deh. Aku cuma kangen sedikit kok, sedikit berlebihan maksudnya.",
    "Kamu tahu diare? Rasa sayang aku ke kamu itu kayak diare, gak bisa ditahan, terus keluar begitu saja.",
    "Sekarang lagi tanggal merah ya? Tenang, aku gak ikut libur mikirin kamu, kok.",
    "Kamu tahu gak rasa sayang aku ke kamu itu kayak kuku. Walaupun dipotong, tetap bakal tumbuh terus.",
    "Kamu tahu bedanya kamu dan Borobudur? Kalo Borobudur itu candi, kalo kamu itu candu.",
    "Aku sama kamu itu udah kayak laptopku sama WiFi kafe. Udah auto-connect.",
    "Kalo jadi superhero, kayaknya aku tahu aku bakal jadi apa. Jadi YourMan.",
    "Kamu tahu gak nama asliku itu Dion. Iya, Dionly man for you.",
    "When I'm in your arms, I feel safe, loved, and I feel like I'm going to be protected from all the stones life can throw.",
    "Thank you for making me feel like the most beautiful woman in the world.",
    "I'm so excited about discovering new things about you and exploring the world through your eyes.",
    "I promise to always love you, even during football season.",
    "The world may crumble around us, but I won't notice because I will be looking into your eyes.",
    "I must be in a museum. Because you're trully a work of art.",
    "Is your name Wifi? Because I am feeling a connection.",
    "The way you look at me makes me feel strong, confident and like I can conquer the world and when I do, I will give it to you.",
    "If love was a storybook, We'd met on the very first page.",
    "Whatever our souls are made of, his and mine are the same.",
    "I'm not sure why you chose me, but I feel like the luckiest man in the world and I hope to live in a way that proves I deserve this honor.",
    "I don't love you despite how weird you are. I love because of how weird you are.",
    "You may not be a painter, but you have colored my life colorful with your smile.",
    "Are you Google? Because you have everything I am searching for.",
    "But we loved with a love that was more than love.",
    "Kamu tau kucing yang paling romantis di dunia? Iya, kucingta padamu.",
    "Minyak, minyak apa yang bikin aku bahagia? Minyaksikan kita duduk berdua di pelaminan.",
    "Kamu tahu bedanya kamu sama buku? Kalau buku itu jendela dunia, kalau kamu itu duniaku.",
    "Kamu tahu kenapa Menara Pisa miring? Iya, soalnya ketarik sama senyum kamu.",
    "Apa perbedaan kamu sama kipas? Kalau kipas bisa bikin angin, kalau kamu bikin angen.",
    "Akhir-akhir ini aku lupa caranya ngikat tali sepatu. Kamu tahu kenapa? Soalnya aku terlalu sibuk ngikat hati kamu.",
    "Apa bedanya kamu sama jam 12.00? Kalau jam 12.00 itu kesiangan, kalau kamu itu kesayangan.",
    "Salep apa yang malah bikin luka tambah parah? Salepas kamu pergi, aku masih berharap kamu kembali.",
    "Apa perbedaan jam dinding sama kamu? Kalau jam dinding itu letaknya di dinding, kalau kamu letaknya di hati aku.",
    "Apa bedanya gitar sama kamu? Kalau gitar dipetik, kalau kamu yang paling cantik.",
        ]