module.exports =[
    'Malem-malem denger kucing berantem, pingin misahin tapi takut lagi ada masalah keluarga.',
    'Lagi pingin meluk kamu dari belakang, terus aku cekik sampai meninggal.',
    'Kamu cantik karena murah senyum, tapi lama-lama jadi kayak orang gila.',
    'Ya tuhan, kalau dia cuman read chat doang kayak gini, ilangin aja HP nya.',
    'Mendingan kita saling sayang aja, daripada saling ngilang.',
    'Mau lari pagi tapi nggak ada yang ngejar, kan males kalau dapet capeknya doang.',
    'Aku dan istriku memutuskan untuk nggak punya anak. Masalahnya kita sudah punya tiga anak.',
    'Bagaimana cara kamu memanggil anjing yang nggak punya kaki? Dipanggil atau tidak, anjing itu nggak akan datang.',
    'Mengapa nama novel coronavirus diganti? Karena terlalu panjang.',
    'Kamu membutuhkan parasut jika ingin terjun payung lebih dari sekali.',
    'Aku nggak tahu operasi ini akan berhasil atau tidak. Karena dokternya adalah mantan pacarku.',
    'Selama ini aku selalu panggil istriku "sayang". Dikiranya aku romantis, padahal aku lupa namanya.',
    'Jangan kagetin pohon pisang, nanti jantungnya copot!',
    'Aku beli obat tidur di warung, kata penjualnya bawanya harus pelan-pelan, takut obatnya bangun.',
    'Emang kamu doang yang top deh, yang lain mah beng-beng.',
    'Gimana cara tercepat untuk sampai ke rumah sakit? Berdiri aja di tengah jalan.',
    'Ada yang lebih sakit dari sakit kepala, yaitu sakit gigi. Yakali sakit hati.',
    'Apa benar kalau mengelilingi Bundaran HI sebanyak tiga kali jadinya Bundaran HIHIHI?',
    'Apa perbedaan kuntilanak dengan cewek zaman sekarang? Kuntilanak pakaiannya lebih sopan.',
    'Waktu itu istri menyuruh saya beli lipgloss. Lalu saya iseng kasih dia lem. Sampai sekarang istri saya nggak mau bicara dengan saya.',
    'Aku punya peliharaan ikan yang bisa break dance. Tapi hanya selama 30 detik dan hanya sekali seumur hidupnya.',
    'Ya Tuhan, kutuklah aku menjadi miliarder tampan. Aku ikhlas.',
    'Kalau aku salah terus di matamu, besok aku pindah ke otakmu.',
    'Nggak usah senyumin aku terus kalau gak niat mengajak berumah tangga.',
    'Cari pacar itu susah, gak segampang di iklan ice cream.',
    'Sayur apa yang paling susah dilupain? Bayam-bayam dirimu.',
    'Begini, yang jumlahnya dua itu mata. Mukanya jangan ikutan ada dua.',
    'Siapa penyanyi Indonesia yang mata duitan? Fulus.',
    'Dengerin kata hati, jangan kata orang. Sekarang banyak orang yang nggak punya hati.',
    'Chatan sama kamu udah kayak introgasi maling. Aku terus yang nanya.',
    'Terkadang saat menutup mata, dunia terlihat gelap.',
    'Niat kerja keras bagai kuda biar cepet kaya, eh malah mati muda.',
    'Kalau playboy nikah sama playgirl, apakah anaknya jadi playstore?',
    'Kalau anak indigo nikah sama anak rumahan, apakah anaknya jadi indihome?',
    'Jangan terlalu meresapi perasaan, meres baju aja udah pegel-pegel.',
    'Kalau sikap kamu dingin terus kayak gini, aku lempar ke gunung api, ya. Biar meleleh.',
    'Jenis burung apa yang bikin bulu kuduk merinding? Camar mayat.',
    'Kalau ada cewek bilang kamu ganteng, bukan berarti dia suka. Dia cuman menghormati ciptaan tuhan.',
    'Kadang tuhan menghadirkan seseorang cuman untuk jadi pengalaman hidup aja.',
    'Wah, bau busuk apa ini? Oh ternyata bau kedengkian dari hatimu.',
    'Katanya tak kenal maka tak sayang. Ini udah kenal, tetep nggak disayang.',
    'Pisang kalau dimakan panas-panas namanya jadi apa? Hihang hoheng.',
    'Kalau dipotong jadi tambah tinggi, apakah itu? Celana.',
    'Makanya kalau mau mikir kakinya dilurusin, biar otaknya nggak ketekuk.',
    'Jus apa yang rasanya pahit? Jus a friend.',
    'Orang bucin telponan sambil ngecas, kalau kesetrum baru tahu rasa.',
    'Kalau kamu jadi matahari aku mau jadi bulan. Biar kita nggak pernah ketemu.',
    'Cita-cita aku mau jadi maling. Karena banyak yang mengejar tanpa mandang fisik.',
    'Gendang apa yang nggak bisa dipukul? Gendang telinga.',
    'Kalau orang Bali nikah sama orang China, apakah nama anaknya jadi I Made in China?',
    'angan pernah berdebat dengan orang yang bodoh, karena orang lain yang melihat tidak akan bisa menebak siapa yang paling bodoh.',
    'Kemarin anak saya demam, terus saya kompres eh malah jadi rar.',
    'Wakil presiden yang sering nonton secara streaming? Muhammad Youtube Kalla.',
    'Burung apa yang bikin merinding? Camar mayat.',
    'Kenapa di Indonesia sering ada pertanyaan ‘kapan nikah?’ Karena Indonesia adalah negara ‘marrytime’.',
    'Gerakan apa yang paling sulit dilakukan? Move on.',
    'Buah apa yang ditakuti oleh mahasiswa? Belimbingan skripsi.',
    'Kalau orang Bali nikah dengan orang China, apakah nama anaknya jadi I Made in China?',
    'Saya punya peliharaan ikan yang bisa break dance, tapi hanya selama 30 detik dan hanya sekali seumur hidup.',
    'Terkadang saat menutup mata, dunia tampak gelap.',
    'Kamu cantik karena murah senyum, tapi lama-lama jadi kayak orang gila.',
    'Bagaimana cara kamu memanggil anjing yang nggak punya kaki? Dipanggil atau tidak, anjing itu nggak akan datang.',
    'Gimana cara tercepat untuk sampai ke rumah sakit? Berdiri aja di tengah jalan.',
    'Apa perbedaan kuntilanak dengan cewek zaman sekarang? Kuntilanak pakaiannya lebih sopan.',
    'Begini, yang jumlahnya dua itu mata. Mukanya jangan ikutan ada dua.',
    'Dengerin kata hati, jangan kata orang. Sekarang banyak orang yang nggak punya hati.',
    'Niat kerja keras bagai kuda biar cepet kaya, eh malah mati muda.',
    'Wah, bau busuk apa ini? Oh ternyata bau kedengkian dari hatimu.',
    'Katanya tak kenal maka tak sayang. Ini udah kenal, tetep nggak disayang.',
    'Jus apa yang rasanya pahit? Jus a friend.',
    'Cita-cita aku mau jadi maling. Karena banyak yang mengejar tanpa mandang fisik.',
    'Kalau kamu jadi matahari aku mau jadi bulan. Biar kita nggak pernah ketemu.',
    'Ya tuhan, kalau dia cuman read chat doang kayak gini, ilangin aja HP nya.',
    'Aku dan istriku memutuskan untuk nggak punya anak. Masalahnya kita sudah punya tiga anak.',
    'Selama ini aku selalu panggil istriku "sayang". Dikiranya aku romantis, padahal aku lupa namanya.',
    '“Duh berat banget,” “Apanya kak?” “Ekspetasi orang tua.”',
    'Malem-malem deket kuburan, pengen nyoba bengong biar kesurupan, malah kepikiran angsuran.',
    '“Mau dianter sampe mana bu?”, “Sampe kesedihan ini berakhir”',
    'Bayangin, ngebonceng temen lu yang Kristen sambil ujan-ujanan terus dia ngebisikin lu “aku membaptis engkau dalam nama bapa..”',
    'Anak brokenhome ga bisa ikut main family 100 soalnya cuman punya 100nya doang familynya ga punya',
]    
