module.exports = [
    'Berwama kuning dan jago berenang? Apa itu? Kotoran manusia',
    'Kenapa tayo warnanya biru? Kalo warna kuning namanya tayi.',
    'Apa surat yang susah untuk dipalsukan? Suratan takdir-',
    'Hewan apa yang diinjak tidak marah? Kera-mik',
    'Kenapa air laut rasanya bisa asin? Karena ikan-ikZ1nya pada berkeringat.',
    'Kenapa anak kodok suka sekali loncat? Namanyajuga an*-anak. ya wajar aja kalo iseng',
    'Sayur apa yang jago nyanyi? Kolplay.',
    'Buah apa yang dulu pernah menjajah Indonesia? Terong Belanda-',
    'Buah apa yang penampilannya tidak segar? Buah alpucat.',
    'Bagian bulu tubuh apa yang bisa bicara? Bulurah.',
    'Kenapa saat ayam berkokok matanya merem? Karena teksnya sudah di',
    'Apa bedanya kamu sama kuburan? Kalo kuburan nyeremin, kalo kamu ngeselin',
    'Apa bedanya sarung sama kotak? Kalo sarung motifnya bisa kotak-kotak.',
    'kalo k0tak nggak bisa sarung-sarung.',
    'Sayur apa yang suka ikut berperang? Saytr mayor.',
    'Nama buah yang paling durhaka? Melon Kundang',
    'Kenapa Sih kerang hidupnya di laut? Soalnya kalo hidupnya di darat namanya kering',
    'Apa bahasa Ingwis dari kata adat? Adat is tiadat.',
    'Orang, orang apa yang kalo lagi berenang dia nggak basah? Orang botak-',
    'Nama sapi apa yang bisa nernpel di tembok? Sapidermen',
    'Telor apa yang kalau diinjak tidak pecah? Telortoar',
    'Ada ga Sih hewan yang hanya terdiri dari satu hurut? Ada dong l kan?',
    'Kuda apa yang selalu jalan ke kiri? Kuda dikunci stang.',
    'Kenapa air mata berwarna bening? Soalnya kalo berwarna hijau namanya air matcha',
    'Kenapa kalau lagi naik sepeda motor bawaannya mau ketawa terus? Soalnya duduknya diatas jokes',
    'Pas kecil tinggalnya di Jawa Barat. pas tua tinggalnya di Sumatera Selatan-siapakah dia?lembang soalnya pas udah tua namanya jadi palembang',
    'Apa nama kota di Jawa Tengah yang iSinya semua bapak-bapak?Purwodaddy',
    'Hewan apa yang jualan rokok? Kodok. soalnya berbunyi rokok-rokok-rokok,',
    'Apa nama kesenian yang selalu dilakukan Oleh nasabah bank? Tari tunai-',
    'Gendang apa yang tidak bisa dipukul? Gendang telinga.',
    'Kalu pisang masih panas kira-kira narnanya jadi apa? Hihang hoheng.',
    'Kalau bundaran HI diputerin sebanyak 3 kali narnanya jadi apa? HIHIHI',
    'Hewan apa yang punya banyak teman? A crab.',
    'Gajah apa yang paling baik? Gajahat.',
    'Apa nama benda yang kalau dibalik jadinya rusak? Kasur.',
    'Ada nggak kendaraan yang bunyinya paling imut? Ada, Kereta api soalnya bunyinya cute cute cute',
    'Barang, barang apa yang kalau dipotong malah tambah tinggi? Celana.',
    'Salah satu keunikan dari penyanyi dangdut adalah bisa hidup sama organ tunggal',
    'Kira-kira kalau pohon pisang dikagetin copot gak yah jantungnya?',
    'Kita perlu nyuci air gak kalo rnau rnasak air?',
    'Kenapa bunyi nyamuk nguung? Soalnya dia minurnnya darah. kalo minum besin bunyiny jadi brumm',
    'Kira-kira kalau baju tidur bangunnya jam berapa?',
    'Anak saya pulang kuliah bonyok soalnya ngambil komputer-',
    'Anak saya kemarin demam. habis itu saya kompres eh tapi malah jadi rar-',
    'Kalo kamu masih mernandang fisik seseorang hal cinta, suruh aja pacaran sama ikan soalnya banyak fisiknya',
    'Saat suami mengusap kepala istri. itu buat memastikan di kepala istrinya tidak ada paku',
    'Kalau beli obat tidur di apotek, pas bawa pulanyya harus hati-hati takut bangun soalnya',
    'Pas mau masak pake panci, pancinya malah jalan sendiri soalnya ternyata panci petualang',
    'Enaknya jadi maling banyak yang ngejar-ngejar dan gapake pandang fisik.',
    'Masih mending kalau kita diselimuti masalah daripada diselimuti wijen jadinya onde-onde',
    'Kalo ngisi bensin motor harus premium supaya ada iklannya.',
    'Kalo kita manasin motor berarti harus direbus apa digoreng?',
    'Coba matahari pracetamol dan inzana pasti nggak akan sepanas ini',
    'Burung apa yang suka bolak balik ke WC? Burung pipit.',
    'Hewan apa yang sangat penting bagi tubuh? Ulat',
    'Hewan apa yang pasti taat lalu lintas? Unta-makan keselarnatan.',
    'Hewan apa yang memiliki banyak keahlian? Kukang. bisa jadi kukang tambal ban,kukang servis motor dan kukang lainnya',
    'Hewan apa yang bisa bikin damai? Adem ayam',
    'Apa yang jauh di mata dekat di hati? Usus',
    'Jus apa yang turun dari langit? Justru itu yang aku enggak tau.',
    'Apa bahasa Indianya bumbu dapur? Tumbar miri jahe.',
    'Apa yang badannya hijau, jalannya mundur, dan kepalanya merah? Obat nyamuk bakar.',
    'Nenek siapa yang jalannya loncat-loncat? Nenek si katak.',
    'Kenapa orang takut kehujanan? Karena hujan beraninya keroyokan, coba kalau satu-satu.',
    'Kenapa baju Batman ada gambar kelalawar? Karena huruf B sudah dipake Bobo.',
    'Kenapa air laut asin? Karena ikannya pada berkeringat.',
    'Apa bedanya sepatu sama jengkol? Sepatu disemir, jengkol disemur.',
    'Apa bedanya antara semut dan orang? Orang bisa kesemutan, semut enggak bisa keorangan.',
    'Apa persamaan kain jemuran dan telepon? Keduanya kalau sudah ‘kriiing’ boleh diangkat.',
    'Apa persamaan tukang sate dan tukang kupat tahu? Sama-sama enggak jual bakso.',
    'Mangga apa yang mengerikan? Mangga-ruk garuk pantat singa.',
    'Apa itu cemilan? Cebelum cepuluh cecudah celapan.',
    'Kopi apa yang bisa mencapit? Kopi ting.',
    'Sapi apa yang larinya cepat? Sapi-da motor.',
    'Ban apa yang sangat berat? Ban-tuin aku dorong.',
    'Lemari apa yang bisa dimasukkin ke kantong? Lemari-buan.',
    'Monyet apa yang berdiri di tepi jalan? Monyet-top angkot.',
    'Cecak apa yang bisa bikin ngap-ngapan? Cecak napas',
    'Kenapa sih kerang hidupnya di laut? Soalnya kalo hidupnya di darat namanya kering.',
    'Pak, barusan saya mau masak, tapi tiba-tiba pancinya jalan sendiri nggak tau ke mana. Ternyata panci petualang.',
    'Kalo kamu masih diselimuti masalah berarti kamu manusia, kao kamu diselimuti wijen berarti onde-onde.',
    'Kenapa nyamuk bunyinya nguung? Karena dia minumnya darah, coba kalo minumnya bensin, bunyinya jadi bruuum.',
    'Kalo cinta masih mandang fisik, suruh aja pacaran sama ikan karena ikan banyak fisiknya.',
    'Saya tadi beli obat tidur di apotek, saya bawa pulang pelan-pelan takut obatnya bangun.',
    'Anak saya ngeyel kuliah malah ngambil komputer, pas pulang ternyata mukanya bonyok.',
    'Di balik usapan tangan suami ke kepala istri, sebenarnya dia ingin memastikan di kepala istrinya nggak ada paku.',
    'Enak ya jadi maling banyak yang ngejar-ngejar dan nggak pake mandang fisik.',
    'Siapa nama asli nyamuk? Tatang! Kan ada lagunya: "Cicak-cicak di dinding. Diam-diam merayap. Tatang seekor nyamuk, hap. Lalu ditangkap..."',
    'Berapa jumlah kaki seekor kerbau? Delapan, yaitu: dua kaki kiri, dua kaki kanan, dua kaki depan, dan dua kaki belakang.',
    'Kalau semua jenis hewan sekolah, siapa yang sering terlambat? Kluwing (kaki seribu). Soalnya kakinya banyak, jadinya kalau pakai sepatu kelamaan.',
    'Apa bedanya balapan kuda sama balapan motor? Balapan kuda ada tempat parkir motor, jika balapan motor tidak ada tempat parkir kuda.',
    'Waktu kecil dia tinggal di Jawa Barat, tapi pas udah tua dia tinggal di Sumatera Selatan, siapa dia? Lembang, soalnya kalau udah udah namanya jadi Pa-Lembang.',
    'Hewan apa yang punya banyak keahlian?Kukang, bisa jadi kukang tambal ban, kukang servis motor, kukang nasi goreng, kukang sol sepatu, dan kukang lainnya.',
    'Kenapa di Indonesia sering ditanyain "Kapan nikah?" Karena indonesia adalah negara "Marrytime".',
    'Kendaraan apa yang bunyinya paling imut? Kereta, naik kereta api cute cute cute...',
    'Bedanya sarung sama kotak apa? Kalo sarung bisa kotak-kotak, kalau kotak nggak bisa sarung-sarung.',
    'Kenapa air mata warnanya bening? Katen kalo air yang warnanya ijo namanya air matcha.',
    'Kenapa kalau lagi naik sepeda motor maunya ketawa terus? Karena dia duduknya di atas jokes.',
    'Kuda apa yang jalannya belok ke kiri terus? Kuda yang dikunci stang.',
    'Kesenian apa yang selalu dilakukan nasabah bank, apakah itu? Tari tunai.',
    'Kenapa anak kodok suka loncat-loncat? Biasalah, namanya juga anak-anak. Suka iseng.',
    'Dia membuat karya, pas jadi hasil karya tersebut diinjak-injak tidak marah, siap coba? Pembuat sandal.',
    'Ada bebek 10 di kali 2 jadi berapa? 8, soalnya yang 2 lagi main di kali.',
    'Rambut putih namanya uban, rambut merah namanya pirang, kalau rambut hijau namanya apa? Rambutan belum mateng.',
    'Kenapa di keyboard komputer ada tulisan "ENTER"? Karena kalau tulisannya "ENTAR", programnya nggak jalan-jalan.',
    'Apa perbedaan antara soto dan coto. Kalau soto dari daging sapi, coto dari daging capi.',
    'Apa nama siput yang kuat dan bawa kera ke mana-mana? Siputa dari gua hantu.',
    'Belut apa yang harus sangat kita hindari? Belut-ang sama teman terus nggak dibayar-bayar.',

]