module.exports = [`
    *BERIKUT ADALAH DAFTAR 32 NAMA SISWA DI KELAS 9.4 :*
    ABDUL HALIM INDRATI
    AMANDA RAHMA PUTRI
    AMORA CLEO OKTRIZA
    ATILLA ABITAMA MARICO
    AULIA FADILAH
    CHELSY CAHAYA SAFITRI
    DINDA AQILLAH PUTRI
    FAHMI IZZATY SABAILATTY
    FAIZ SYAQRI RAMDA SAAD
    FARELT RIYANDI PRATAMA
    FARHAN BERLI ADZANATS
    FERDYAN PRATAMA
    GHEO VATHRIAND
    LUKMAN AL FARISI
    M. FAREL RAMADHAN
    MOZZHATI SORI
    MUHAMMAD ASYROF
    MUHAMMAD FAJAR
    MUHAMMAD RADI HAZIZIE
    MUTHIA DINA
    NAIMA HADANA
    NAJWA GHASSANI
    ONZELLE IFTIHAL ARTA
    PNIEL ZEBUA
    RAHMANISA LAILA MAHARANI
    RASSYA ARITYA
    SALSA FITRIANA
    SHILVA FRISHINI AZRI
    SIDDIQ INSAN SYAHADA
    SUCY NABILA PUTRI
    VIVI APRIANI
    ZAQKY PUTRA KURNIAWAN`
]